[M] implement watcher for error
tef-github/freqtrade pull request #39
Opened 2022-07-02 09:50 UTC by Bemhreth

2022-07-02 12:35 UTC, Bemhreth commented
**test results **
*result of creenLogBBRsiScalp_1.91.txt = * https://t.me/c/1658942980/10215
*result of creenLogBBRsiScalp_1.90.txt = * https://t.me/c/1658942980/10218
*result of creenLogBBRsiScalp_1.86.txt = * https://t.me/c/1658942980/10219

2022-07-04 15:06 UTC, tef-github requested changes
changes requested

2022-07-04 15:06 UTC, tef-github commented on wao/_error_watcher.py
> +class _Error_Watcher(watchdog.events.PatternMatchingEventHandler):
rename to Error_Watcher and error_watcher.py

2022-07-04 15:06 UTC, tef-github commented on wao/brain_config.py
> +    _FREQTRADE_LOGS_DIRECTORY = FREQTRADE_PATH + "/logs/"
_WAO_LOGS_DIRECTORY

2022-07-06 04:37 UTC, tef-github commented on wao/brain_util.py
> +def setup():
create_watchers

2022-07-06 04:37 UTC, tef-github requested changes
CR

2022-07-09 20:13 UTC, tef-github commented on wao/brain_config.py
> +    IS_ERROR_WATCHER_ENABLED = False
I will set this to true after merging

2022-07-09 20:13 UTC, tef-github approved these changes

2022-07-09 20:13 UTC, merged