[M] Code artifact
tef-github/freqtrade pull request #61
Opened 2022-10-01 09:42 UTC by Bemhreth

**test result**
<img width="740" alt="Screen Shot 2015-01-21 at 12 10 26 PM" src="https://user-images.githubusercontent.com/44050394/193403371-6a1db869-eb10-4bbc-b170-ddb3d96b2d1f.png">

2022-10-01 17:10 UTC, tef-github requested changes
CR

2022-10-01 17:10 UTC, tef-github commented on wao/notifier.py
> -sys.path.append(BrainConfig.EXECUTION_PATH)
Can we remove EXECUTION_PATH from brain_config.py

2022-10-04 03:22 UTC, tef-github commented
@Bemhreth don't we need to create the directories that were migrated from execution to here manually ?
the ones that start with underscore

2022-10-04 03:25 UTC, tef-github commented
@Bemhreth Good job! I don't have many code comments on this one. Let's wait till all prs are ready + artifact is stable (without bugs) and we will merge them together at the same time.

2022-10-04 19:59 UTC, Bemhreth commented
> @Bemhreth don't we need to create the directories that were migrated from execution to here manually ? the ones that start with underscore

we have create directory for those files so those functions will create the directories needed but if there is any folder that doesn't have one I will search and create one for them.

2022-10-06 02:28 UTC, tef-github requested changes
cr

2022-10-06 02:28 UTC, tef-github commented on wao/brain_config.py
> +    BRAIN = "Freq_Cluc6werk"
add a comment //set from strategy files

2022-10-06 02:28 UTC, tef-github commented on wao/wao_strategy_controller.py
> +        BrainConfig.BRAIN = brain
set this in strategy files and remove self.brain from strategies and WaoStrategyController

remove all references and parameters

wherever it's used at the end, replace by BrainConfig.BRAIN

2022-10-06 17:37 UTC, tef-github approved these changes
LGTM, let's wait before merge

2022-10-08 21:02 UTC, tef-github requested changes
This is APPROVED. Waiting for google sheet records.

2022-10-10 15:12 UTC, tef-github approved these changes

2022-10-10 15:13 UTC, merged